apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "taas.fullname" . }}-migrate
  labels:
    {{- include "taas.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
        {{- include "taas.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: {{ include "taas.image" (dict "image" .Values.api.image "global" .Values.image) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: {{ include "taas.fullname" . }}-config
            - secretRef:
                name: {{ include "taas.fullname" . }}-secret
